import os
import sys
import time
os.system("apt install neofetch")
os.system("neofetch")
os.system("apt install figlet")
os.system("termux-setup-storage ")
os.system("figlet welcome")
print(" \u001b[31m")
print("[1] insta-followers")
print("[2] number-ban")
u_choice=int(input('Choose a option:  '))
if u_choice==1:
     os.system("clear")
     print("Processing please wait -")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait /")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait |")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait \ ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait - ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait /")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait |")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait \ ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait - ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait /")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait |")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait \ ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait - ")
     time.sleep(1)
     os.system("clear")
     time.sleep(1)
     os.system("cp App/instagram-followers.apk /sdcard ")
     print("check your files")
if u_choice==2:
     print(" \u001b[36m")
     os.system("neofetch")
     os.system("clear")
     print("Processing please wait -")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait /")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait |")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait \ ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait - ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait /")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait |")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait \ ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait - ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait /")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait |")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait \ ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait - ")
     time.sleep(1)
     os.system("clear")
     time.sleep(1)
     os.system("cp App/number-ban.apk /sdcard")
     print("check your files")
